# I. Numpy

### Импортируйте NumPy

In [2]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [4]:
x= np.zeros(10)
x[5]=1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [7]:
z = x.reshape((5, 2))
print(z)

[[0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [11]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
b=a[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [20]:
#четные элементы
mask=b % 2==0
print(b[mask])

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [21]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [25]:
a=np.random.random(((4,3,2)))
min, max=a.min(), a.max()
print(min, max)


0.08945431540136783 0.9761555565265962


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [51]:
a=np.random.randint(0, 10, (6,4))
b=np.random.randint(0, 10, (4,3))
ab=np.dot(a,b)
print("матрица a")
print (a)
print("матрица b")
print (b)
print("матрица ab")
print (ab)

матрица a
[[9 9 5 4]
 [6 6 8 1]
 [0 7 6 5]
 [6 8 1 1]
 [2 6 7 3]
 [2 8 4 5]]
матрица b
[[0 7 2]
 [9 0 8]
 [1 7 1]
 [6 6 6]]
матрица ab
[[110 122 119]
 [ 68 104  74]
 [ 99  72  92]
 [ 79  55  83]
 [ 79  81  77]
 [106  72 102]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [52]:
a=np.random.randint(0, 10, (7,7))
sred=a.mean()
s_t_d=a.std()
print(a)
print(sred, s_t_d)

[[0 9 8 1 9 8 2]
 [1 9 9 8 7 9 7]
 [7 9 1 8 2 8 5]
 [8 7 6 4 3 6 3]
 [8 6 9 0 0 4 9]
 [8 1 1 4 7 2 3]
 [8 9 1 7 5 7 7]]
5.510204081632653 3.064759863280511


In [67]:
def normalize(a):
    return (a-a.mean(axis=0))/a.std(axis=0)
normalis=normalize(a)
print(normalis)

[[-1.71814712  0.67583782  0.83666003 -1.18378431  1.44672847  0.74136248
  -1.30088727]
 [-1.41747137  0.67583782  1.1155467   1.13643294  0.77158852  1.17382392
   0.76870611]
 [ 0.3865831   0.67583782 -1.1155467   1.13643294 -0.91626136  0.74136248
  -0.05913124]
 [ 0.68725885 -0.05198752  0.27888668 -0.18940549 -0.57869139 -0.12356041
  -0.88696859]
 [ 0.68725885 -0.4159002   1.1155467  -1.51524392 -1.59140131 -0.9884833
   1.59654347]
 [ 0.68725885 -2.23546355 -1.1155467  -0.18940549  0.77158852 -1.85340619
  -0.88696859]
 [ 0.68725885  0.67583782 -1.1155467   0.80497333  0.09644856  0.30890103
   0.76870611]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [3]:
import pandas as pd
import matplotlib as mp
import seaborn as sns



### Загрузите датасет Tips из набора датасетов seaborn

In [4]:
tips_df = sns.load_dataset('tips')

### Посмотрите на первые 5 строчек

In [5]:
tips_df.head(5)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Узнайте сколько всего строчек и колонок в данных

In [8]:
tips_df.shape

(244, 7)

### Проверьте есть ли пропуски в данных

In [18]:
print("Кол-во пропусков в данных")
tips_df.isnull().sum()


Кол-во пропусков в данных


total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

x

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

In [22]:
tips_df.loc[:,"total_bill"].max()

50.81

### Найдите количество курящих людей

In [24]:
tips_df.loc(tips_df[:,"smoker"]=="yes")

InvalidIndexError: (slice(None, None, None), 'smoker')

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.